version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=5000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=cloud_api_security_checker
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - AWS_ACCESS_KEY_ID=your_aws_access_key_id
      - AWS_SECRET_ACCESS_KEY=your_aws_secret_access_key
      - AZURE_SUBSCRIPTION_ID=your_azure_subscription_id
      - AZURE_CLIENT_ID=your_azure_client_id
      - AZURE_CLIENT_SECRET=your_azure_client_secret
      - AZURE_TENANT_ID=your_azure_tenant_id
      - GCP_PROJECT_ID=your_gcp_project_id
      - GCP_SERVICE_ACCOUNT_FILE=your_gcp_service_account_file_path
      - OAUTH2_CLIENT_ID=your_oauth2_client_id
      - OAUTH2_CLIENT_SECRET=your_oauth2_client_secret
      - OAUTH2_REDIRECT_URI=your_oauth2_redirect_uri
      - LOG_LEVEL=INFO
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=cloud_api_security_checker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
